language: node_js

node_js:
  - 10

cache:
  yarn: true
  directories:
  - node_modules

install:
  - yarn

script:
  - yarn build-storybook

deploy:
  provider: s3
  bucket: "{{cookiecutter.s3_bucket_storybook}}"
  skip_cleanup: true
  local_dir: storybook-static
  acl: public_read
