language: python
python:
- '3.6'
matrix:
  fast_finish: true
install: pip install -U tox-travis
script: tox
notifications:
  email:
    on_success: change
    on_failure: always
deploy:
  access_key_id:
    secure: IK/VXlwdTVFg9vSCvtGf/yZ9iBxHBEQPPR1rC4yObND4JqQ0syFofL3d+ijGmC4xAaVPn8DmIojmXrt5wK6DYHjF06Sj+UiVKfRsYYeIXIRgaETFuFKEXCYeWUJ2cN+jRzEHi+ExNHsqKCz9/v43dgncvK1Ho762T432hteFR2LPa3BwIcBMosylPViB4yO7sp5yxmZ7zGvXUgIQRayyZhhPku8bE3FLgseh7b9pUfnWQdveIHICmNnBc+SoC962667/j66yXzjj7RddkMhGX2RSt5TRYbeTULfXWBI4Y0G8X4DHZsntMFyzg/AQZtkqfWXUotTAwbEO0LD8FjgeQGRuVZDhFBUsKqE/k5ZpwleMcIHs98IZOF5c1q+FF4nsW9iNaQ5EyzMvj/RAD52j90j8UxPriRQnDLBSEkvUsiOG6svefazI3kn8pmf6kxs7932lW8vr9K+AHBh6VmrJXE/TINjhhRqe1cZGUo6J/H+SX2Ov+iojOrEO9k8GDp1kUXIaDmFbtq9/hQ8Pp1kgU6ybdC5B7BIiKt98NWMK/cr3N/XJ2c/KUuZxGtf82HEf6936pPJJYs4iu4yhsrEb9Pj7hd4hSbZQz0e62oO9MglUTHALAh6Bx/tmpLxsUc9+EyIjRxbjqCqWB4ZonvO2wakITD5dMY4EKWkhN/WsMmQ=
